# Generated by Django 5.2.1 on 2025-07-01 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_initial_filieres_niveaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_requests_etudiant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='subject',
            field=models.CharField(default='Sans Sujet', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_requests_enseignant', to=settings.AUTH_USER_MODEL),
        ),
    ]
