# Generated by Django 5.2.1 on 2025-06-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_helprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='last_name',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(default='temp', max_length=30, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(default='temp', max_length=30, verbose_name='Prénom'),
            preserve_default=False,
        ),
    ]
