# Generated by Django 5.2.1 on 2025-06-04 05:31


from django.db import migrations

def transfert_noms(apps, schema_editor):
    """Copie first_name/last_name vers prenom/nom pour les anciens comptes"""
    Enseignant = apps.get_model('api', 'Enseignant')
    for user in Enseignant.objects.all():
        if hasattr(user, 'first_name'):  # Vérifie si l'ancien champ existe
            user.prenom = user.first_name
            user.nom = user.last_name
            user.save()
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_enseignant_first_name_and_more'),
    ]

    operations = [
        migrations.RunPython(transfert_noms, migrations.RunPython.noop),
    ]
